# Generated by Django 5.1.3 on 2024-11-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('merchant_category', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant_type', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('city_size', models.CharField(blank=True, max_length=20, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('card_present', models.BooleanField(null=True)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.CharField(blank=True, max_length=20, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('distance_from_home', models.BooleanField(null=True)),
                ('high_risk_merchant', models.BooleanField(null=True)),
                ('transaction_hour', models.SmallIntegerField()),
                ('weekend_transaction', models.BooleanField(null=True)),
                ('v_num_transactions', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('v_total_amount', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('v_unique_merchants', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('v_unique_countries', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('v_max_single_amount', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('is_fraud', models.BooleanField()),
            ],
        ),
    ]
