# Generated by Django 5.1.3 on 2024-12-04 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudDetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
                ('dataset_size', models.IntegerField()),
                ('training_data_start_date', models.DateField()),
                ('training_data_end_date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detailed_performance', models.JSONField()),
                ('metadata', models.JSONField()),
                ('model_file', models.BinaryField()),
                ('is_deployed', models.BooleanField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
