# Generated by Django 5.1.3 on 2024-12-04 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="version_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
