# Generated by Django 5.1.3 on 2024-12-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_frauddetectionmodel'),
        ('detector', '0002_transaction_version_date'),
    ]

    operations = [
    ]
