# ========================= VARIABLES ======================== #

variables:
  # The path to our k8n agent
  KUBE_CONTEXT: "courses/dit826/2024/group1:fraud-detection"

# ========================== STAGES ========================== #

stages:
  - pre-build-check
  - build
  - test
  - versioning
  - deploy

# =========================== JOBS =========================== #

# --------------------------- pre-build-check --------------------------- #

env_test:
  stage: pre-build-check
  tags:
    - docker
  script:
    - |
      if grep -q "jupyter" environment.yml || \
          grep -q "notebook" environment.yml || \
          grep -q "nbformat" environment.yml || \
          grep -q "nbclient" environment.yml || \
          grep -q "nbconvert" environment.yml; then
        echo "Jupyter libraries should not be here because it becomes too slow";
        exit 1;
      else
        echo "No problems found";
      fi
# --------------------------- build -------------------------- #
# NOTE - inspired by https://docs.gitlab.com/ee/user/packages/container_registry/build_and_push_images.html
build_docker_image:
  stage: build
  image: docker:latest
  tags:
    - docker-build # Tag for gitlab-runner that can build images
  services:
    - docker:dind # dind service for building the image in the runners container
  script:
    # Logs in to the GitLab Container Registry using standard environment variables
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    # Buildes the image for right platform
    - docker build --platform linux/amd64 -t "$CI_REGISTRY_IMAGE/backend:latest" -f ./fraud_detection/dockerfile .
    # Pushes the image to the GitLab Container Registry
    - docker push "$CI_REGISTRY_IMAGE/backend:latest"
  # rules:
  #   # Only runs for pushes to main
  #   - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  #     # ... and if the fraud_detection folder has changed
  #     changes:
  #       - fraud_detection/**
  #       - gx/**
  #   - when: never

# -------------------------- version ------------------------- #
version_new_model:
  # Use docker runner
  tags:
    - docker
  # Use the latest version of Ubuntu as the base image
  image: ubuntu:latest
  # This job is part of the versioning stage
  stage: versioning
  rules:
    # This job runs only for merge requests and if the target brach is main
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      # A new model is detected if changes are made to the db_setup or ML_pipeline folders
      changes:
        - db_setup/**
        - fraud_detection/detector/services/ml_pipeline/**
    - when: never
  # Install required tools
  before_script:
    - apt-get update && apt-get install -y curl jq
  script:
    - |
      echo "New model detected"
      echo "Current model version: ${LATEST_MODEL_VERSION}"
      # Extract the current model version
      V=$(echo "${LATEST_MODEL_VERSION}" | cut -d. -f1) # Extract V from LATEST_MODEL_VERSION
      NEW_VERSION=$((V + 1)).0
      # Update the variable via the GitLab API
      curl --header "PRIVATE-TOKEN: ${GITLAB_ACCESS_TOKEN}" \
           --request PUT \
           --form "value=${NEW_VERSION}" \
           "https://git.chalmers.se/api/v4/projects/${CI_PROJECT_ID}/variables/LATEST_MODEL_VERSION"
      # Confirm that the new version was updated
      UPDATED_VERSION=$(curl --header "PRIVATE-TOKEN: ${GITLAB_ACCESS_TOKEN}" \
                             "https://git.chalmers.se/api/v4/projects/${CI_PROJECT_ID}/variables/LATEST_MODEL_VERSION" | jq -r '.value')
      echo "Updated model version: ${UPDATED_VERSION}"
      # Create and push the new tag
      echo "Creating new tag"
      curl --request POST \
           --header "PRIVATE-TOKEN: ${GITLAB_ACCESS_TOKEN}" \
           --url "https://git.chalmers.se/api/v4/projects/${CI_PROJECT_ID}/repository/tags" \
           --data "tag_name=${UPDATED_VERSION}" \
           --data "ref=${CI_COMMIT_BRANCH}" \
           --data "message=New model version: ${UPDATED_VERSION}"

# -------------------------- deploy -------------------------- #

deploy_to_k8s:
  tags:
    - docker
  stage: deploy
  image:
    name: bitnami/kubectl:latest # Image that has the kubectl tool
    entrypoint: [""]
  script:
    - kubectl config use-context $KUBE_CONTEXT # Sets the context to the correct cluster connection
    - kubectl apply -f deployment.yml # Applies the deployment file incase it has changed

    # This forces the pods to restart with the new image. Not a good practice but otherwise it will
    # try to spawn another pod with the new image. That will cause our storage usage to be exceeded
    # so it will freeze, which is just awesome. This causes a tiny amount of downtime, no big deal.
    - kubectl delete pods -l app=backend

  rules:
    # Only runs for pushes to main
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      # ... and if the fraud_detection folder or the deployment configuration has changed
      changes:
        - fraud_detection/**
        - gx/**
        - deployment.yml
    - when: never
