apiVersion: apps/v1 # specifies kubernetes api version
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets: # uses the docker-registry secret to access the private registry
        - name: docker-registry
      containers:
        - name: backend
          image: registry.git.chalmers.se/courses/dit826/2024/group1/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: RUN_MODE
              value: "prod" # allowed values are "dev" and "prod"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 6
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 # the port the service listens on
      targetPort: 8000 # the port the container listens on

